// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6gusGFBMtIYWzN_pFNTkU5UGu7vDU_v8',
    appId: '1:414543069387:web:3bbbd1b08740969f0d9b4e',
    messagingSenderId: '414543069387',
    projectId: 'needai-7f3d1',
    authDomain: 'needai-7f3d1.firebaseapp.com',
    storageBucket: 'needai-7f3d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDatA2g17JLiTJxvZd9ZUFImLkI0NIISlI',
    appId: '1:414543069387:android:d26ebe6ad436cbc00d9b4e',
    messagingSenderId: '414543069387',
    projectId: 'needai-7f3d1',
    storageBucket: 'needai-7f3d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ZsU30g-BzPqMY7cVr3AyQeBIHhxdNrQ',
    appId: '1:414543069387:ios:a2924c747bbadb7c0d9b4e',
    messagingSenderId: '414543069387',
    projectId: 'needai-7f3d1',
    storageBucket: 'needai-7f3d1.firebasestorage.app',
    androidClientId: '414543069387-0meiqun7gkqiudu4hiq9713aaeltn55i.apps.googleusercontent.com',
    iosClientId: '414543069387-vtsu4jbiq9llb7a3kshvk77qor2rr1t7.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpaiTeachers',
  );
}
